version: "3"
services:
  scylla:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "127.0.0.1:8899:8899"
      - "127.0.0.1:8081:8081"
    volumes:
      - /var/www/scylla:/var/www/scylla
