version: '3.8'

services:
  scylla:
    build:
      context: .
      target: prod
    volumes:
      - /var/www/scylla:/var/www/scylla
    ports:
      - "127.0.0.1:8899:8899"
      - "127.0.0.1:8081:8081"
