FROM python:3.9-alpine as build

RUN apk add --update --no-cache g++ gcc libxslt-dev make build-base curl curl-dev openssl-dev patch

RUN mkdir -p /var/www/scylla
WORKDIR /var/www/scylla

RUN pip install scylla

COPY 70b7050abe.patch ./
RUN cd /usr/local/lib/python3.9/site-packages \
    && patch -p1 < /var/www/scylla/70b7050abe.patch

FROM python:3.9-alpine

LABEL maintainer="WildCat <wildcat.name@gmail.com>"

RUN apk add --update --no-cache libxslt-dev curl-dev

COPY --from=build /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

WORKDIR /var/www/scylla
VOLUME /var/www/scylla

EXPOSE 8899
EXPOSE 8081

CMD python -m scylla
